theme: jekyll-theme-hacker
title: Safe Notes
description: Safe Notes is a security project aimed at providing an encrypted, private note manager that works locally and protects notes from various threat actors.
show_downloads: "true"
